name: javadoc

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
      - name: Merge master -> gh-pages
        run: |
          git fetch origin gh-pages
          git checkout gh-pages
          git merge main --allow-unrelated-histories
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '18'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Generate Javadoc Site
        run: ./gradlew javadoc
      - name: Deploy Javadoc site
        run: |
          git add .
          git commit -m "Publish javadoc"
          git push