name: Javadoc Site Generation

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge master -> gh-pages
        run: |
          git fetch origin gh-pages
          git checkout gh-pages
          git merge master --allow-unrelated-histories
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '18'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Generate Javadoc Site
        run: ./gradlew javadoc
      - name: Deploy Javadoc site
        run: |
          git add .
          git commit -m "Publish javadoc"
          git push